### ISSUE TITLE
Unable to support new record class, etc

### ISSUE THREAD

**Issue by wf-soft** [aelij/RoslynPad#373]
![image](https://user-images.githubusercontent.com/62228539/98760362-18413200-240e-11eb-8775-9e8c04ca9df6.png)
![image](https://user-images.githubusercontent.com/62228539/98760390-22633080-240e-11eb-8769-98ae509eea1d.png)

**Comment by aelij** [comment]
Fixed in 8c79943b50ceeade60775bbca6f85176a0dd8f7f

**Comment by Mike737377** [comment]
@aelij 
Looks like it's still an issue in 15.1

![Screenshot_042621_042916_PM](https://user-images.githubusercontent.com/1201203/116038252-8b80ec80-a6ac-11eb-97f8-738cc5cd6e08.jpg)

**Comment by SBhojani** [comment]
The issue seems to be related to the version of .Net Core selected in the drop down. I got that error with .Net Core 5.0.205 but the same code worked fine with .Net Core 2.2.207.

**Comment by xparadoxical** [comment]
Still occurs, with .net 6.0.101 as well. This should be reopened @aelij
